"use client"

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StrictMode, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { BarChart3, Home, Plus, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [location, setLocation] = useState<typeof window.location | null>(null);

  useEffect(() => {
    // Only runs on the client-side
    if (typeof window !== "undefined") {
      setLocation(window.location);
    }
  }, []); // Empty dependency array means this runs only once, after the component mounts

  const navItems = [
    { path: "/", icon: Home, label: "Home" },
    { path: "/create", icon: Plus, label: "Create" },
    { path: "/reports", icon: BarChart3, label: "Reports" },
  ];

  const isActive = (path: string): boolean => {
    if (!location) return false; // Make sure location is available
    return location.pathname === path;
  };

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/vite.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Better Food Logs - Track Your Nutrition</title>
        <meta
          name="description"
          content="Log your meals instantly with smart search. Track nutrition, create custom food records, and monitor your progress."
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StrictMode>
          <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-blue-50">
            {/* Header */}
            <header className="bg-white/80 backdrop-blur-sm border-b border-emerald-100 sticky top-0 z-50">
              <div className="max-w-4xl mx-auto px-4 py-4">
                <div className="flex items-center justify-between">
                  <Link href="/" className="flex items-center space-x-2">
                    <div className="w-8 h-8 bg-gradient-to-r from-emerald-500 to-blue-500 rounded-lg flex items-center justify-center">
                      <span className="text-white font-bold text-sm">BFL</span>
                    </div>
                    <h1 className="text-xl font-bold bg-gradient-to-r from-emerald-600 to-blue-600 bg-clip-text text-transparent">
                      Better Food Logs
                    </h1>
                  </Link>

                  <button className="flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-emerald-500 to-blue-500 text-white rounded-lg hover:shadow-lg transition-all duration-200">
                    <User size={16} />
                    <span className="text-sm">Sign In</span>
                  </button>
                </div>
              </div>
            </header>

            {/* Main Content */}
            <main className="max-w-4xl mx-auto px-4 py-6">
              {children}
              <Link
                href="https://bolt.new/"
                className="flex gap-1 pt-2 items-center justify-end w-full italic hover:underline"
                target="_blank"
                rel="noreferrer"
              >
                <span>Made with ❤️ and</span>

                <Image
                  src="/white_circle_360x360.png"
                  alt="Made with Bolt"
                  width={32}
                  height={32}
                  className="inline size-8"
                />
              </Link>
            </main>

            {/* Bottom Navigation */}
            <nav className="fixed bottom-0 left-0 right-0 bg-white/90 backdrop-blur-sm border-t border-emerald-100">
              <div className="max-w-4xl mx-auto px-4">
                <div className="flex justify-around py-2">
                  {navItems.map(({ path, icon: Icon, label }) => (
                    <Link
                      key={path}
                      href={path}
                      className={`flex flex-col items-center py-2 px-4 transition-all duration-200 ${
                        isActive(path)
                          ? "text-emerald-600"
                          : "text-gray-500 hover:text-emerald-500"
                      }`}
                    >
                      <Icon size={20} />
                      <span className="text-xs mt-1">{label}</span>
                    </Link>
                  ))}
                </div>
              </div>
            </nav>

            {/* Bottom padding to account for fixed navigation */}
            <div className="h-16"></div>
          </div>
        </StrictMode>
      </body>
    </html>
  );
}
