import { Food } from '../types';

export const sampleFoods: Food[] = 
[
  {
    "id": 1,
    "name": "Apple",
    "servingDescription": "1 medium (182g)",
    "servingMassG": 182,
    "servingVolumeMl": 0,
    "calories": 95,
    "proteinG": 0.5,
    "fatG": 0.3,
    "carbsG": 25,
    "sugarG": 19,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 2,
    "name": "Chicken Breast",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 142,
    "proteinG": 26.7,
    "fatG": 3.1,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 63,
    "cholesterolMg": 73
  },
  {
    "id": 3,
    "name": "Brown Rice",
    "servingDescription": "1 cup cooked (195g)",
    "servingMassG": 195,
    "servingVolumeMl": 0,
    "calories": 216,
    "proteinG": 5,
    "fatG": 1.8,
    "carbsG": 45,
    "sugarG": 1,
    "sodiumMg": 10,
    "cholesterolMg": 0
  },
  {
    "id": 4,
    "name": "Broccoli",
    "servingDescription": "1 cup chopped (91g)",
    "servingMassG": 91,
    "servingVolumeMl": 0,
    "calories": 31,
    "proteinG": 2.6,
    "fatG": 0.3,
    "carbsG": 6,
    "sugarG": 1.5,
    "sodiumMg": 30,
    "cholesterolMg": 0
  },
  {
    "id": 5,
    "name": "Greek Yogurt",
    "servingDescription": "1 container (150g)",
    "servingMassG": 150,
    "servingVolumeMl": 0,
    "calories": 100,
    "proteinG": 17,
    "fatG": 0.7,
    "carbsG": 6,
    "sugarG": 4,
    "sodiumMg": 50,
    "cholesterolMg": 5
  },
  {
    "id": 6,
    "name": "Banana",
    "servingDescription": "1 medium (118g)",
    "servingMassG": 118,
    "servingVolumeMl": 0,
    "calories": 105,
    "proteinG": 1.3,
    "fatG": 0.3,
    "carbsG": 27,
    "sugarG": 14,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 7,
    "name": "Whole Milk",
    "servingDescription": "1 cup (244g)",
    "servingMassG": 244,
    "servingVolumeMl": 240,
    "calories": 149,
    "proteinG": 7.7,
    "fatG": 8,
    "carbsG": 12,
    "sugarG": 12,
    "sodiumMg": 105,
    "cholesterolMg": 24
  },
  {
    "id": 8,
    "name": "Egg (whole)",
    "servingDescription": "1 large (50g)",
    "servingMassG": 50,
    "servingVolumeMl": 0,
    "calories": 72,
    "proteinG": 6.3,
    "fatG": 5,
    "carbsG": 0.4,
    "sugarG": 0.4,
    "sodiumMg": 71,
    "cholesterolMg": 186
  },
  {
    "id": 9,
    "name": "Avocado",
    "servingDescription": "1/2 medium (100g)",
    "servingMassG": 100,
    "servingVolumeMl": 0,
    "calories": 160,
    "proteinG": 2,
    "fatG": 15,
    "carbsG": 9,
    "sugarG": 0.7,
    "sodiumMg": 7,
    "cholesterolMg": 0
  },
  {
    "id": 10,
    "name": "Salmon (wild)",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 155,
    "proteinG": 22,
    "fatG": 7,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 50,
    "cholesterolMg": 50
  },
  {
    "id": 11,
    "name": "Oatmeal",
    "servingDescription": "1 cup cooked (234g)",
    "servingMassG": 234,
    "servingVolumeMl": 0,
    "calories": 154,
    "proteinG": 6,
    "fatG": 3,
    "carbsG": 27,
    "sugarG": 1,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 12,
    "name": "White Rice",
    "servingDescription": "1 cup cooked (158g)",
    "servingMassG": 158,
    "servingVolumeMl": 0,
    "calories": 205,
    "proteinG": 4.3,
    "fatG": 0.4,
    "carbsG": 45,
    "sugarG": 0.1,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 13,
    "name": "Whole Wheat Bread",
    "servingDescription": "1 slice (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 69,
    "proteinG": 3.6,
    "fatG": 1.1,
    "carbsG": 12,
    "sugarG": 1.6,
    "sodiumMg": 132,
    "cholesterolMg": 0
  },
  {
    "id": 14,
    "name": "Cheddar Cheese",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 115,
    "proteinG": 7,
    "fatG": 9.4,
    "carbsG": 0.4,
    "sugarG": 0.1,
    "sodiumMg": 174,
    "cholesterolMg": 30
  },
  {
    "id": 15,
    "name": "Butter",
    "servingDescription": "1 tbsp (14g)",
    "servingMassG": 14,
    "servingVolumeMl": 0,
    "calories": 102,
    "proteinG": 0.1,
    "fatG": 11.5,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 91,
    "cholesterolMg": 31
  },
  {
    "id": 16,
    "name": "Olive Oil",
    "servingDescription": "1 tbsp (14g)",
    "servingMassG": 14,
    "servingVolumeMl": 15,
    "calories": 119,
    "proteinG": 0,
    "fatG": 14,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 0,
    "cholesterolMg": 0
  },
  {
    "id": 17,
    "name": "Potato (white)",
    "servingDescription": "1 medium (173g)",
    "servingMassG": 173,
    "servingVolumeMl": 0,
    "calories": 161,
    "proteinG": 4.3,
    "fatG": 0.2,
    "carbsG": 37,
    "sugarG": 1.7,
    "sodiumMg": 17,
    "cholesterolMg": 0
  },
  {
    "id": 18,
    "name": "Sweet Potato",
    "servingDescription": "1 medium (130g)",
    "servingMassG": 130,
    "servingVolumeMl": 0,
    "calories": 112,
    "proteinG": 2,
    "fatG": 0.1,
    "carbsG": 26,
    "sugarG": 5.4,
    "sodiumMg": 72,
    "cholesterolMg": 0
  },
  {
    "id": 19,
    "name": "Pasta (cooked)",
    "servingDescription": "1 cup (140g)",
    "servingMassG": 140,
    "servingVolumeMl": 0,
    "calories": 221,
    "proteinG": 8,
    "fatG": 1.3,
    "carbsG": 43,
    "sugarG": 0.8,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 20,
    "name": "Ground Beef (85% lean)",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 218,
    "proteinG": 22,
    "fatG": 13,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 76,
    "cholesterolMg": 76
  },
  {
    "id": 21,
    "name": "Pork Chop",
    "servingDescription": "1 chop (113g)",
    "servingMassG": 113,
    "servingVolumeMl": 0,
    "calories": 221,
    "proteinG": 29,
    "fatG": 11,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 60,
    "cholesterolMg": 77
  },
  {
    "id": 22,
    "name": "Tuna (canned in water)",
    "servingDescription": "1 can drained (165g)",
    "servingMassG": 165,
    "servingVolumeMl": 0,
    "calories": 191,
    "proteinG": 42,
    "fatG": 1.4,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 648,
    "cholesterolMg": 66
  },
  {
    "id": 23,
    "name": "Shrimp",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 84,
    "proteinG": 18,
    "fatG": 0.9,
    "carbsG": 0.2,
    "sugarG": 0,
    "sodiumMg": 190,
    "cholesterolMg": 166
  },
  {
    "id": 24,
    "name": "Black Beans",
    "servingDescription": "1 cup cooked (172g)",
    "servingMassG": 172,
    "servingVolumeMl": 0,
    "calories": 227,
    "proteinG": 15,
    "fatG": 0.9,
    "carbsG": 41,
    "sugarG": 0.6,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 25,
    "name": "Chickpeas",
    "servingDescription": "1 cup cooked (164g)",
    "servingMassG": 164,
    "servingVolumeMl": 0,
    "calories": 269,
    "proteinG": 14.5,
    "fatG": 4.2,
    "carbsG": 45,
    "sugarG": 7.9,
    "sodiumMg": 11,
    "cholesterolMg": 0
  },
  {
    "id": 26,
    "name": "Lentils",
    "servingDescription": "1 cup cooked (198g)",
    "servingMassG": 198,
    "servingVolumeMl": 0,
    "calories": 230,
    "proteinG": 18,
    "fatG": 0.8,
    "carbsG": 40,
    "sugarG": 3.6,
    "sodiumMg": 4,
    "cholesterolMg": 0
  },
  {
    "id": 27,
    "name": "Spinach",
    "servingDescription": "1 cup raw (30g)",
    "servingMassG": 30,
    "servingVolumeMl": 0,
    "calories": 7,
    "proteinG": 0.9,
    "fatG": 0.1,
    "carbsG": 1.1,
    "sugarG": 0.1,
    "sodiumMg": 24,
    "cholesterolMg": 0
  },
  {
    "id": 28,
    "name": "Carrot",
    "servingDescription": "1 medium (61g)",
    "servingMassG": 61,
    "servingVolumeMl": 0,
    "calories": 25,
    "proteinG": 0.6,
    "fatG": 0.1,
    "carbsG": 6,
    "sugarG": 2.9,
    "sodiumMg": 42,
    "cholesterolMg": 0
  },
  {
    "id": 29,
    "name": "Tomato",
    "servingDescription": "1 medium (123g)",
    "servingMassG": 123,
    "servingVolumeMl": 0,
    "calories": 22,
    "proteinG": 1.1,
    "fatG": 0.2,
    "carbsG": 4.8,
    "sugarG": 3.2,
    "sodiumMg": 6,
    "cholesterolMg": 0
  },
  {
    "id": 30,
    "name": "Cucumber",
    "servingDescription": "1/2 medium (100g)",
    "servingMassG": 100,
    "servingVolumeMl": 0,
    "calories": 16,
    "proteinG": 0.7,
    "fatG": 0.1,
    "carbsG": 3.6,
    "sugarG": 1.7,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 31,
    "name": "Bell Pepper",
    "servingDescription": "1 medium (119g)",
    "servingMassG": 119,
    "servingVolumeMl": 0,
    "calories": 24,
    "proteinG": 1,
    "fatG": 0.2,
    "carbsG": 6,
    "sugarG": 4.2,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 32,
    "name": "Onion",
    "servingDescription": "1 medium (110g)",
    "servingMassG": 110,
    "servingVolumeMl": 0,
    "calories": 44,
    "proteinG": 1.2,
    "fatG": 0.1,
    "carbsG": 10,
    "sugarG": 4.7,
    "sodiumMg": 4,
    "cholesterolMg": 0
  },
  {
    "id": 33,
    "name": "Garlic",
    "servingDescription": "3 cloves (9g)",
    "servingMassG": 9,
    "servingVolumeMl": 0,
    "calories": 13,
    "proteinG": 0.6,
    "fatG": 0,
    "carbsG": 3,
    "sugarG": 0.1,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 34,
    "name": "Mushrooms",
    "servingDescription": "1 cup sliced (70g)",
    "servingMassG": 70,
    "servingVolumeMl": 0,
    "calories": 15,
    "proteinG": 2.2,
    "fatG": 0.2,
    "carbsG": 2.3,
    "sugarG": 1.4,
    "sodiumMg": 4,
    "cholesterolMg": 0
  },
  {
    "id": 35,
    "name": "Corn (sweet)",
    "servingDescription": "1 ear (90g)",
    "servingMassG": 90,
    "servingVolumeMl": 0,
    "calories": 77,
    "proteinG": 2.9,
    "fatG": 1.1,
    "carbsG": 17,
    "sugarG": 6.4,
    "sodiumMg": 15,
    "cholesterolMg": 0
  },
  {
    "id": 36,
    "name": "Peas",
    "servingDescription": "1 cup (160g)",
    "servingMassG": 160,
    "servingVolumeMl": 0,
    "calories": 117,
    "proteinG": 8,
    "fatG": 0.6,
    "carbsG": 21,
    "sugarG": 8,
    "sodiumMg": 7,
    "cholesterolMg": 0
  },
  {
    "id": 37,
    "name": "Yogurt (plain)",
    "servingDescription": "1 cup (245g)",
    "servingMassG": 245,
    "servingVolumeMl": 240,
    "calories": 149,
    "proteinG": 8.5,
    "fatG": 8,
    "carbsG": 11,
    "sugarG": 11,
    "sodiumMg": 113,
    "cholesterolMg": 31
  },
  {
    "id": 38,
    "name": "Cottage Cheese",
    "servingDescription": "1/2 cup (113g)",
    "servingMassG": 113,
    "servingVolumeMl": 0,
    "calories": 98,
    "proteinG": 11,
    "fatG": 4.3,
    "carbsG": 3.4,
    "sugarG": 2.7,
    "sodiumMg": 364,
    "cholesterolMg": 17
  },
  {
    "id": 39,
    "name": "Mozzarella Cheese",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 85,
    "proteinG": 6.3,
    "fatG": 6.3,
    "carbsG": 1,
    "sugarG": 0.3,
    "sodiumMg": 138,
    "cholesterolMg": 22
  },
  {
    "id": 40,
    "name": "Ham",
    "servingDescription": "3 oz (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 105,
    "proteinG": 14,
    "fatG": 4,
    "carbsG": 1.5,
    "sugarG": 1.5,
    "sodiumMg": 830,
    "cholesterolMg": 38
  },
  {
    "id": 41,
    "name": "Turkey Breast",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 125,
    "proteinG": 26,
    "fatG": 1,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 55,
    "cholesterolMg": 62
  },
  {
    "id": 42,
    "name": "Pork Bacon",
    "servingDescription": "2 slices (16g)",
    "servingMassG": 16,
    "servingVolumeMl": 0,
    "calories": 87,
    "proteinG": 6,
    "fatG": 7,
    "carbsG": 0.2,
    "sugarG": 0,
    "sodiumMg": 376,
    "cholesterolMg": 18
  },
  {
    "id": 43,
    "name": "Tortilla (corn)",
    "servingDescription": "1 tortilla (24g)",
    "servingMassG": 24,
    "servingVolumeMl": 0,
    "calories": 52,
    "proteinG": 1.4,
    "fatG": 0.7,
    "carbsG": 11,
    "sugarG": 0.2,
    "sodiumMg": 11,
    "cholesterolMg": 0
  },
  {
    "id": 44,
    "name": "Tortilla (wheat)",
    "servingDescription": "1 tortilla (36g)",
    "servingMassG": 36,
    "servingVolumeMl": 0,
    "calories": 110,
    "proteinG": 3.7,
    "fatG": 2.5,
    "carbsG": 19,
    "sugarG": 1.1,
    "sodiumMg": 210,
    "cholesterolMg": 0
  },
  {
    "id": 45,
    "name": "Pizza (cheese slice)",
    "servingDescription": "1 slice (107g)",
    "servingMassG": 107,
    "servingVolumeMl": 0,
    "calories": 285,
    "proteinG": 12,
    "fatG": 10,
    "carbsG": 36,
    "sugarG": 4,
    "sodiumMg": 640,
    "cholesterolMg": 18
  },
  {
    "id": 46,
    "name": "Hamburger (beef patty)",
    "servingDescription": "1 sandwich (100g)",
    "servingMassG": 100,
    "servingVolumeMl": 0,
    "calories": 254,
    "proteinG": 12,
    "fatG": 9,
    "carbsG": 29,
    "sugarG": 5,
    "sodiumMg": 511,
    "cholesterolMg": 35
  },
  {
    "id": 47,
    "name": "Hot Dog",
    "servingDescription": "1 hot dog (52g)",
    "servingMassG": 52,
    "servingVolumeMl": 0,
    "calories": 151,
    "proteinG": 5,
    "fatG": 13,
    "carbsG": 2,
    "sugarG": 1,
    "sodiumMg": 507,
    "cholesterolMg": 30
  },
  {
    "id": 48,
    "name": "French Fries",
    "servingDescription": "1 medium (117g)",
    "servingMassG": 117,
    "servingVolumeMl": 0,
    "calories": 365,
    "proteinG": 3.4,
    "fatG": 17,
    "carbsG": 48,
    "sugarG": 0.3,
    "sodiumMg": 246,
    "cholesterolMg": 0
  },
  {
    "id": 49,
    "name": "Tortilla Chips",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 138,
    "proteinG": 2,
    "fatG": 7,
    "carbsG": 18,
    "sugarG": 0.1,
    "sodiumMg": 115,
    "cholesterolMg": 0
  },
  {
    "id": 50,
    "name": "Chocolate Bar",
    "servingDescription": "1 bar (43g)",
    "servingMassG": 43,
    "servingVolumeMl": 0,
    "calories": 210,
    "proteinG": 2,
    "fatG": 13,
    "carbsG": 25,
    "sugarG": 24,
    "sodiumMg": 35,
    "cholesterolMg": 8
  },
  {
    "id": 51,
    "name": "Ice Cream (vanilla scoop)",
    "servingDescription": "1/2 cup (66g)",
    "servingMassG": 66,
    "servingVolumeMl": 0,
    "calories": 137,
    "proteinG": 2.3,
    "fatG": 7.3,
    "carbsG": 16,
    "sugarG": 14,
    "sodiumMg": 53,
    "cholesterolMg": 29
  },
  {
    "id": 52,
    "name": "Peanut Butter",
    "servingDescription": "2 tbsp (32g)",
    "servingMassG": 32,
    "servingVolumeMl": 0,
    "calories": 188,
    "proteinG": 8,
    "fatG": 16,
    "carbsG": 6,
    "sugarG": 3,
    "sodiumMg": 136,
    "cholesterolMg": 0
  },
  {
    "id": 53,
    "name": "Almonds",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 164,
    "proteinG": 6,
    "fatG": 14,
    "carbsG": 6,
    "sugarG": 1.2,
    "sodiumMg": 0,
    "cholesterolMg": 0
  },
  {
    "id": 54,
    "name": "Walnuts",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 185,
    "proteinG": 4.3,
    "fatG": 18,
    "carbsG": 4,
    "sugarG": 0.7,
    "sodiumMg": 1,
    "cholesterolMg": 0
  },
  {
    "id": 55,
    "name": "Cashews",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 157,
    "proteinG": 5,
    "fatG": 12,
    "carbsG": 9,
    "sugarG": 1.7,
    "sodiumMg": 3,
    "cholesterolMg": 0
  },
  {
    "id": 56,
    "name": "Bread (white)",
    "servingDescription": "1 slice (25g)",
    "servingMassG": 25,
    "servingVolumeMl": 0,
    "calories": 67,
    "proteinG": 2,
    "fatG": 0.8,
    "carbsG": 13,
    "sugarG": 1.4,
    "sodiumMg": 127,
    "cholesterolMg": 0
  },
  {
    "id": 57,
    "name": "Bagel",
    "servingDescription": "1 medium (98g)",
    "servingMassG": 98,
    "servingVolumeMl": 0,
    "calories": 277,
    "proteinG": 11,
    "fatG": 1.4,
    "carbsG": 55,
    "sugarG": 6,
    "sodiumMg": 443,
    "cholesterolMg": 0
  },
  {
    "id": 58,
    "name": "Cereal (corn flakes)",
    "servingDescription": "1 cup (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 100,
    "proteinG": 2,
    "fatG": 0.1,
    "carbsG": 24,
    "sugarG": 2.7,
    "sodiumMg": 200,
    "cholesterolMg": 0
  },
  {
    "id": 59,
    "name": "Granola",
    "servingDescription": "1/2 cup (50g)",
    "servingMassG": 50,
    "servingVolumeMl": 0,
    "calories": 200,
    "proteinG": 4,
    "fatG": 6,
    "carbsG": 32,
    "sugarG": 12,
    "sodiumMg": 60,
    "cholesterolMg": 0
  },
  {
    "id": 60,
    "name": "Pancakes (2 medium)",
    "servingDescription": "2 medium (86g)",
    "servingMassG": 86,
    "servingVolumeMl": 0,
    "calories": 175,
    "proteinG": 4.8,
    "fatG": 4.8,
    "carbsG": 28,
    "sugarG": 4.2,
    "sodiumMg": 420,
    "cholesterolMg": 38
  },
  {
    "id": 61,
    "name": "Waffles (2)",
    "servingDescription": "2 waffles (70g)",
    "servingMassG": 70,
    "servingVolumeMl": 0,
    "calories": 218,
    "proteinG": 5.6,
    "fatG": 7,
    "carbsG": 33,
    "sugarG": 6,
    "sodiumMg": 383,
    "cholesterolMg": 38
  },
  {
    "id": 62,
    "name": "French Toast (1 slice)",
    "servingDescription": "1 slice (65g)",
    "servingMassG": 65,
    "servingVolumeMl": 0,
    "calories": 149,
    "proteinG": 6.4,
    "fatG": 5.4,
    "carbsG": 19,
    "sugarG": 4.2,
    "sodiumMg": 210,
    "cholesterolMg": 99
  },
  {
    "id": 63,
    "name": "Coffee (8oz)",
    "servingDescription": "1 cup (237ml)",
    "servingMassG": 237,
    "servingVolumeMl": 237,
    "calories": 2,
    "proteinG": 0.3,
    "fatG": 0,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 5,
    "cholesterolMg": 0
  },
  {
    "id": 64,
    "name": "Tea (8oz)",
    "servingDescription": "1 cup (237ml)",
    "servingMassG": 237,
    "servingVolumeMl": 237,
    "calories": 2,
    "proteinG": 0,
    "fatG": 0,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 7,
    "cholesterolMg": 0
  },
  {
    "id": 65,
    "name": "Orange Juice (8oz)",
    "servingDescription": "1 cup (240ml)",
    "servingMassG": 240,
    "servingVolumeMl": 240,
    "calories": 112,
    "proteinG": 1.7,
    "fatG": 0.5,
    "carbsG": 26,
    "sugarG": 21,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 66,
    "name": "Soda (12oz)",
    "servingDescription": "1 can (355ml)",
    "servingMassG": 355,
    "servingVolumeMl": 355,
    "calories": 140,
    "proteinG": 0,
    "fatG": 0,
    "carbsG": 39,
    "sugarG": 39,
    "sodiumMg": 45,
    "cholesterolMg": 0
  },
  {
    "id": 67,
    "name": "Beer (12oz)",
    "servingDescription": "1 can (355ml)",
    "servingMassG": 355,
    "servingVolumeMl": 355,
    "calories": 153,
    "proteinG": 1.6,
    "fatG": 0,
    "carbsG": 13,
    "sugarG": 0,
    "sodiumMg": 14,
    "cholesterolMg": 0
  },
  {
    "id": 68,
    "name": "Wine (5oz)",
    "servingDescription": "5 oz (147ml)",
    "servingMassG": 147,
    "servingVolumeMl": 147,
    "calories": 123,
    "proteinG": 0.1,
    "fatG": 0,
    "carbsG": 4,
    "sugarG": 1,
    "sodiumMg": 5,
    "cholesterolMg": 0
  },
  {
    "id": 69,
    "name": "Water (500ml)",
    "servingDescription": "500ml",
    "servingMassG": 500,
    "servingVolumeMl": 500,
    "calories": 0,
    "proteinG": 0,
    "fatG": 0,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 0,
    "cholesterolMg": 0
  },
  {
    "id": 70,
    "name": "Tofu",
    "servingDescription": "1/2 cup (126g)",
    "servingMassG": 126,
    "servingVolumeMl": 0,
    "calories": 94,
    "proteinG": 10,
    "fatG": 6,
    "carbsG": 2.3,
    "sugarG": 0.6,
    "sodiumMg": 9,
    "cholesterolMg": 0
  },
  {
    "id": 71,
    "name": "Tempeh",
    "servingDescription": "1/2 cup (83g)",
    "servingMassG": 83,
    "servingVolumeMl": 0,
    "calories": 160,
    "proteinG": 15,
    "fatG": 9,
    "carbsG": 9,
    "sugarG": 0,
    "sodiumMg": 9,
    "cholesterolMg": 0
  },
  {
    "id": 72,
    "name": "Edamame",
    "servingDescription": "1/2 cup shelled (78g)",
    "servingMassG": 78,
    "servingVolumeMl": 0,
    "calories": 94,
    "proteinG": 9,
    "fatG": 4,
    "carbsG": 7,
    "sugarG": 2,
    "sodiumMg": 4,
    "cholesterolMg": 0
  },
  {
    "id": 73,
    "name": "Quinoa",
    "servingDescription": "1 cup cooked (185g)",
    "servingMassG": 185,
    "servingVolumeMl": 0,
    "calories": 222,
    "proteinG": 8.1,
    "fatG": 3.6,
    "carbsG": 39,
    "sugarG": 1.6,
    "sodiumMg": 13,
    "cholesterolMg": 0
  },
  {
    "id": 74,
    "name": "Barley",
    "servingDescription": "1 cup cooked (157g)",
    "servingMassG": 157,
    "servingVolumeMl": 0,
    "calories": 193,
    "proteinG": 3.6,
    "fatG": 0.7,
    "carbsG": 44,
    "sugarG": 0.4,
    "sodiumMg": 6,
    "cholesterolMg": 0
  },
  {
    "id": 75,
    "name": "Millet",
    "servingDescription": "1 cup cooked (174g)",
    "servingMassG": 174,
    "servingVolumeMl": 0,
    "calories": 207,
    "proteinG": 6.1,
    "fatG": 1.7,
    "carbsG": 41,
    "sugarG": 0.2,
    "sodiumMg": 3,
    "cholesterolMg": 0
  },
  {
    "id": 76,
    "name": "Couscous",
    "servingDescription": "1 cup cooked (157g)",
    "servingMassG": 157,
    "servingVolumeMl": 0,
    "calories": 176,
    "proteinG": 6,
    "fatG": 0.3,
    "carbsG": 36,
    "sugarG": 0.2,
    "sodiumMg": 8,
    "cholesterolMg": 0
  },
  {
    "id": 77,
    "name": "Sausage (pork link)",
    "servingDescription": "1 link (45g)",
    "servingMassG": 45,
    "servingVolumeMl": 0,
    "calories": 148,
    "proteinG": 5.5,
    "fatG": 13,
    "carbsG": 1.1,
    "sugarG": 0.7,
    "sodiumMg": 379,
    "cholesterolMg": 30
  },
  {
    "id": 78,
    "name": "Salami",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 110,
    "proteinG": 6,
    "fatG": 9,
    "carbsG": 0.5,
    "sugarG": 0.2,
    "sodiumMg": 430,
    "cholesterolMg": 24
  },
  {
    "id": 79,
    "name": "Pepperoni",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 138,
    "proteinG": 5.5,
    "fatG": 12,
    "carbsG": 0.6,
    "sugarG": 0.1,
    "sodiumMg": 493,
    "cholesterolMg": 20
  },
  {
    "id": 80,
    "name": "Meatballs (beef)",
    "servingDescription": "3 medium (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 200,
    "proteinG": 14,
    "fatG": 14,
    "carbsG": 4,
    "sugarG": 1,
    "sodiumMg": 400,
    "cholesterolMg": 60
  },
  {
    "id": 81,
    "name": "Fish (cod)",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 70,
    "proteinG": 15,
    "fatG": 0.6,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 60,
    "cholesterolMg": 37
  },
  {
    "id": 82,
    "name": "Shrimp (fried)",
    "servingDescription": "3 oz (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 206,
    "proteinG": 13,
    "fatG": 13,
    "carbsG": 10,
    "sugarG": 0.5,
    "sodiumMg": 570,
    "cholesterolMg": 130
  },
  {
    "id": 83,
    "name": "Chicken Thigh",
    "servingDescription": "1 thigh (80g)",
    "servingMassG": 80,
    "servingVolumeMl": 0,
    "calories": 109,
    "proteinG": 13,
    "fatG": 6,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 50,
    "cholesterolMg": 63
  },
  {
    "id": 84,
    "name": "Duck Breast",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 170,
    "proteinG": 23,
    "fatG": 8,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 55,
    "cholesterolMg": 76
  },
  {
    "id": 85,
    "name": "Lamb Chop",
    "servingDescription": "1 chop (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 210,
    "proteinG": 17,
    "fatG": 15,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 53,
    "cholesterolMg": 65
  },
  {
    "id": 86,
    "name": "Beef Steak (sirloin)",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 180,
    "proteinG": 24,
    "fatG": 8,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 55,
    "cholesterolMg": 70
  },
  {
    "id": 87,
    "name": "Beef Steak (ribeye)",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 210,
    "proteinG": 23,
    "fatG": 13,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 55,
    "cholesterolMg": 70
  },
  {
    "id": 88,
    "name": "Pork Ribs",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 270,
    "proteinG": 20,
    "fatG": 20,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 75,
    "cholesterolMg": 70
  },
  {
    "id": 89,
    "name": "Clams",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 126,
    "proteinG": 22,
    "fatG": 2,
    "carbsG": 4,
    "sugarG": 0,
    "sodiumMg": 95,
    "cholesterolMg": 57
  },
  {
    "id": 90,
    "name": "Oysters",
    "servingDescription": "6 medium (84g)",
    "servingMassG": 84,
    "servingVolumeMl": 0,
    "calories": 69,
    "proteinG": 8,
    "fatG": 2,
    "carbsG": 4,
    "sugarG": 0,
    "sodiumMg": 90,
    "cholesterolMg": 42
  },
  {
    "id": 91,
    "name": "Mussels",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 146,
    "proteinG": 20,
    "fatG": 4,
    "carbsG": 6,
    "sugarG": 0,
    "sodiumMg": 286,
    "cholesterolMg": 48
  },
  {
    "id": 92,
    "name": "Crab",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 71,
    "proteinG": 15,
    "fatG": 0.8,
    "carbsG": 0,
    "sugarG": 0,
    "sodiumMg": 321,
    "cholesterolMg": 45
  },
  {
    "id": 93,
    "name": "Lobster",
    "servingDescription": "3 oz cooked (85g)",
    "servingMassG": 85,
    "servingVolumeMl": 0,
    "calories": 76,
    "proteinG": 16,
    "fatG": 0.7,
    "carbsG": 1.1,
    "sugarG": 0,
    "sodiumMg": 423,
    "cholesterolMg": 72
  },
  {
    "id": 94,
    "name": "Pumpkin",
    "servingDescription": "1 cup cooked (245g)",
    "servingMassG": 245,
    "servingVolumeMl": 0,
    "calories": 49,
    "proteinG": 2,
    "fatG": 0.2,
    "carbsG": 12,
    "sugarG": 5,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 95,
    "name": "Zucchini",
    "servingDescription": "1 cup sliced (124g)",
    "servingMassG": 124,
    "servingVolumeMl": 0,
    "calories": 21,
    "proteinG": 1.5,
    "fatG": 0.4,
    "carbsG": 3.9,
    "sugarG": 2.4,
    "sodiumMg": 9,
    "cholesterolMg": 0
  },
  {
    "id": 96,
    "name": "Eggplant",
    "servingDescription": "1 cup cooked (99g)",
    "servingMassG": 99,
    "servingVolumeMl": 0,
    "calories": 35,
    "proteinG": 0.8,
    "fatG": 0.2,
    "carbsG": 8.6,
    "sugarG": 3.2,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 97,
    "name": "Cabbage",
    "servingDescription": "1 cup chopped (89g)",
    "servingMassG": 89,
    "servingVolumeMl": 0,
    "calories": 22,
    "proteinG": 1.1,
    "fatG": 0.1,
    "carbsG": 5.2,
    "sugarG": 2.8,
    "sodiumMg": 16,
    "cholesterolMg": 0
  },
  {
    "id": 98,
    "name": "Kale",
    "servingDescription": "1 cup chopped (67g)",
    "servingMassG": 67,
    "servingVolumeMl": 0,
    "calories": 33,
    "proteinG": 2.2,
    "fatG": 0.6,
    "carbsG": 6,
    "sugarG": 1.3,
    "sodiumMg": 25,
    "cholesterolMg": 0
  },
  {
    "id": 99,
    "name": "Lettuce",
    "servingDescription": "1 cup shredded (36g)",
    "servingMassG": 36,
    "servingVolumeMl": 0,
    "calories": 5,
    "proteinG": 0.5,
    "fatG": 0.1,
    "carbsG": 1,
    "sugarG": 0.5,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 100,
    "name": "Rice Cakes",
    "servingDescription": "1 cake (9g)",
    "servingMassG": 9,
    "servingVolumeMl": 0,
    "calories": 35,
    "proteinG": 0.7,
    "fatG": 0.1,
    "carbsG": 7.3,
    "sugarG": 0,
    "sodiumMg": 7,
    "cholesterolMg": 0
  },
  {
    "id": 101,
    "name": "Popcorn (air-popped)",
    "servingDescription": "3 cups (24g)",
    "servingMassG": 24,
    "servingVolumeMl": 0,
    "calories": 93,
    "proteinG": 3,
    "fatG": 1.1,
    "carbsG": 18.6,
    "sugarG": 0.2,
    "sodiumMg": 2,
    "cholesterolMg": 0
  },
  {
    "id": 102,
    "name": "Pretzels",
    "servingDescription": "1 oz (28g)",
    "servingMassG": 28,
    "servingVolumeMl": 0,
    "calories": 108,
    "proteinG": 2.7,
    "fatG": 0.8,
    "carbsG": 22,
    "sugarG": 0.8,
    "sodiumMg": 354,
    "cholesterolMg": 0
  },
  {
    "id": 103,
    "name": "Granola Bar",
    "servingDescription": "1 bar (24g)",
    "servingMassG": 24,
    "servingVolumeMl": 0,
    "calories": 100,
    "proteinG": 2,
    "fatG": 3,
    "carbsG": 17,
    "sugarG": 7,
    "sodiumMg": 65,
    "cholesterolMg": 0
  },
  {
    "id": 104,
    "name": "Protein Shake",
    "servingDescription": "1 scoop (30g) with water",
    "servingMassG": 30,
    "servingVolumeMl": 0,
    "calories": 120,
    "proteinG": 24,
    "fatG": 1,
    "carbsG": 3,
    "sugarG": 1,
    "sodiumMg": 50,
    "cholesterolMg": 50
  },
  {
    "id": 105,
    "name": "Smoothie",
    "servingDescription": "1 cup (240ml)",
    "servingMassG": 240,
    "servingVolumeMl": 240,
    "calories": 130,
    "proteinG": 2,
    "fatG": 1,
    "carbsG": 31,
    "sugarG": 23,
    "sodiumMg": 20,
    "cholesterolMg": 0
  }
];