import { Food } from '../types';

export const sampleFoods: Food[] = 
[  {
    "id": 1,
    "name": "Apple",
    "serving_description": "1 medium (182g)",
    "serving_mass_g": 182,
    "serving_volume_ml": 0,
    "calories": 95,
    "protein_g": 0.5,
    "fat_g": 0.3,
    "carbs_g": 25,
    "sugar_g": 19,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 2,
    "name": "Chicken Breast",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 142,
    "protein_g": 26.7,
    "fat_g": 3.1,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 63,
    "cholesterol_mg": 73
  },
  {
    "id": 3,
    "name": "Brown Rice",
    "serving_description": "1 cup cooked (195g)",
    "serving_mass_g": 195,
    "serving_volume_ml": 0,
    "calories": 216,
    "protein_g": 5,
    "fat_g": 1.8,
    "carbs_g": 45,
    "sugar_g": 1,
    "sodium_mg": 10,
    "cholesterol_mg": 0
  },
  {
    "id": 4,
    "name": "Broccoli",
    "serving_description": "1 cup chopped (91g)",
    "serving_mass_g": 91,
    "serving_volume_ml": 0,
    "calories": 31,
    "protein_g": 2.6,
    "fat_g": 0.3,
    "carbs_g": 6,
    "sugar_g": 1.5,
    "sodium_mg": 30,
    "cholesterol_mg": 0
  },
  {
    "id": 5,
    "name": "Greek Yogurt",
    "serving_description": "1 container (150g)",
    "serving_mass_g": 150,
    "serving_volume_ml": 0,
    "calories": 100,
    "protein_g": 17,
    "fat_g": 0.7,
    "carbs_g": 6,
    "sugar_g": 4,
    "sodium_mg": 50,
    "cholesterol_mg": 5
  },
  {
    "id": 6,
    "name": "Banana",
    "serving_description": "1 medium (118g)",
    "serving_mass_g": 118,
    "serving_volume_ml": 0,
    "calories": 105,
    "protein_g": 1.3,
    "fat_g": 0.3,
    "carbs_g": 27,
    "sugar_g": 14,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 7,
    "name": "Whole Milk",
    "serving_description": "1 cup (244g)",
    "serving_mass_g": 244,
    "serving_volume_ml": 240,
    "calories": 149,
    "protein_g": 7.7,
    "fat_g": 8,
    "carbs_g": 12,
    "sugar_g": 12,
    "sodium_mg": 105,
    "cholesterol_mg": 24
  },
  {
    "id": 8,
    "name": "Egg (whole)",
    "serving_description": "1 large (50g)",
    "serving_mass_g": 50,
    "serving_volume_ml": 0,
    "calories": 72,
    "protein_g": 6.3,
    "fat_g": 5,
    "carbs_g": 0.4,
    "sugar_g": 0.4,
    "sodium_mg": 71,
    "cholesterol_mg": 186
  },
  {
    "id": 9,
    "name": "Avocado",
    "serving_description": "1/2 medium (100g)",
    "serving_mass_g": 100,
    "serving_volume_ml": 0,
    "calories": 160,
    "protein_g": 2,
    "fat_g": 15,
    "carbs_g": 9,
    "sugar_g": 0.7,
    "sodium_mg": 7,
    "cholesterol_mg": 0
  },
  {
    "id": 10,
    "name": "Salmon (wild)",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 155,
    "protein_g": 22,
    "fat_g": 7,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 50,
    "cholesterol_mg": 50
  },
  {
    "id": 11,
    "name": "Oatmeal",
    "serving_description": "1 cup cooked (234g)",
    "serving_mass_g": 234,
    "serving_volume_ml": 0,
    "calories": 154,
    "protein_g": 6,
    "fat_g": 3,
    "carbs_g": 27,
    "sugar_g": 1,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 12,
    "name": "White Rice",
    "serving_description": "1 cup cooked (158g)",
    "serving_mass_g": 158,
    "serving_volume_ml": 0,
    "calories": 205,
    "protein_g": 4.3,
    "fat_g": 0.4,
    "carbs_g": 45,
    "sugar_g": 0.1,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 13,
    "name": "Whole Wheat Bread",
    "serving_description": "1 slice (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 69,
    "protein_g": 3.6,
    "fat_g": 1.1,
    "carbs_g": 12,
    "sugar_g": 1.6,
    "sodium_mg": 132,
    "cholesterol_mg": 0
  },
  {
    "id": 14,
    "name": "Cheddar Cheese",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 115,
    "protein_g": 7,
    "fat_g": 9.4,
    "carbs_g": 0.4,
    "sugar_g": 0.1,
    "sodium_mg": 174,
    "cholesterol_mg": 30
  },
  {
    "id": 15,
    "name": "Butter",
    "serving_description": "1 tbsp (14g)",
    "serving_mass_g": 14,
    "serving_volume_ml": 0,
    "calories": 102,
    "protein_g": 0.1,
    "fat_g": 11.5,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 91,
    "cholesterol_mg": 31
  },
  {
    "id": 16,
    "name": "Olive Oil",
    "serving_description": "1 tbsp (14g)",
    "serving_mass_g": 14,
    "serving_volume_ml": 15,
    "calories": 119,
    "protein_g": 0,
    "fat_g": 14,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 0,
    "cholesterol_mg": 0
  },
  {
    "id": 17,
    "name": "Potato (white)",
    "serving_description": "1 medium (173g)",
    "serving_mass_g": 173,
    "serving_volume_ml": 0,
    "calories": 161,
    "protein_g": 4.3,
    "fat_g": 0.2,
    "carbs_g": 37,
    "sugar_g": 1.7,
    "sodium_mg": 17,
    "cholesterol_mg": 0
  },
  {
    "id": 18,
    "name": "Sweet Potato",
    "serving_description": "1 medium (130g)",
    "serving_mass_g": 130,
    "serving_volume_ml": 0,
    "calories": 112,
    "protein_g": 2,
    "fat_g": 0.1,
    "carbs_g": 26,
    "sugar_g": 5.4,
    "sodium_mg": 72,
    "cholesterol_mg": 0
  },
  {
    "id": 19,
    "name": "Pasta (cooked)",
    "serving_description": "1 cup (140g)",
    "serving_mass_g": 140,
    "serving_volume_ml": 0,
    "calories": 221,
    "protein_g": 8,
    "fat_g": 1.3,
    "carbs_g": 43,
    "sugar_g": 0.8,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 20,
    "name": "Ground Beef (85% lean)",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 218,
    "protein_g": 22,
    "fat_g": 13,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 76,
    "cholesterol_mg": 76
  },
  {
    "id": 21,
    "name": "Pork Chop",
    "serving_description": "1 chop (113g)",
    "serving_mass_g": 113,
    "serving_volume_ml": 0,
    "calories": 221,
    "protein_g": 29,
    "fat_g": 11,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 60,
    "cholesterol_mg": 77
  },
  {
    "id": 22,
    "name": "Tuna (canned in water)",
    "serving_description": "1 can drained (165g)",
    "serving_mass_g": 165,
    "serving_volume_ml": 0,
    "calories": 191,
    "protein_g": 42,
    "fat_g": 1.4,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 648,
    "cholesterol_mg": 66
  },
  {
    "id": 23,
    "name": "Shrimp",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 84,
    "protein_g": 18,
    "fat_g": 0.9,
    "carbs_g": 0.2,
    "sugar_g": 0,
    "sodium_mg": 190,
    "cholesterol_mg": 166
  },
  {
    "id": 24,
    "name": "Black Beans",
    "serving_description": "1 cup cooked (172g)",
    "serving_mass_g": 172,
    "serving_volume_ml": 0,
    "calories": 227,
    "protein_g": 15,
    "fat_g": 0.9,
    "carbs_g": 41,
    "sugar_g": 0.6,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 25,
    "name": "Chickpeas",
    "serving_description": "1 cup cooked (164g)",
    "serving_mass_g": 164,
    "serving_volume_ml": 0,
    "calories": 269,
    "protein_g": 14.5,
    "fat_g": 4.2,
    "carbs_g": 45,
    "sugar_g": 7.9,
    "sodium_mg": 11,
    "cholesterol_mg": 0
  },
  {
    "id": 26,
    "name": "Lentils",
    "serving_description": "1 cup cooked (198g)",
    "serving_mass_g": 198,
    "serving_volume_ml": 0,
    "calories": 230,
    "protein_g": 18,
    "fat_g": 0.8,
    "carbs_g": 40,
    "sugar_g": 3.6,
    "sodium_mg": 4,
    "cholesterol_mg": 0
  },
  {
    "id": 27,
    "name": "Spinach",
    "serving_description": "1 cup raw (30g)",
    "serving_mass_g": 30,
    "serving_volume_ml": 0,
    "calories": 7,
    "protein_g": 0.9,
    "fat_g": 0.1,
    "carbs_g": 1.1,
    "sugar_g": 0.1,
    "sodium_mg": 24,
    "cholesterol_mg": 0
  },
  {
    "id": 28,
    "name": "Carrot",
    "serving_description": "1 medium (61g)",
    "serving_mass_g": 61,
    "serving_volume_ml": 0,
    "calories": 25,
    "protein_g": 0.6,
    "fat_g": 0.1,
    "carbs_g": 6,
    "sugar_g": 2.9,
    "sodium_mg": 42,
    "cholesterol_mg": 0
  },
  {
    "id": 29,
    "name": "Tomato",
    "serving_description": "1 medium (123g)",
    "serving_mass_g": 123,
    "serving_volume_ml": 0,
    "calories": 22,
    "protein_g": 1.1,
    "fat_g": 0.2,
    "carbs_g": 4.8,
    "sugar_g": 3.2,
    "sodium_mg": 6,
    "cholesterol_mg": 0
  },
  {
    "id": 30,
    "name": "Cucumber",
    "serving_description": "1/2 medium (100g)",
    "serving_mass_g": 100,
    "serving_volume_ml": 0,
    "calories": 16,
    "protein_g": 0.7,
    "fat_g": 0.1,
    "carbs_g": 3.6,
    "sugar_g": 1.7,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 31,
    "name": "Bell Pepper",
    "serving_description": "1 medium (119g)",
    "serving_mass_g": 119,
    "serving_volume_ml": 0,
    "calories": 24,
    "protein_g": 1,
    "fat_g": 0.2,
    "carbs_g": 6,
    "sugar_g": 4.2,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 32,
    "name": "Onion",
    "serving_description": "1 medium (110g)",
    "serving_mass_g": 110,
    "serving_volume_ml": 0,
    "calories": 44,
    "protein_g": 1.2,
    "fat_g": 0.1,
    "carbs_g": 10,
    "sugar_g": 4.7,
    "sodium_mg": 4,
    "cholesterol_mg": 0
  },
  {
    "id": 33,
    "name": "Garlic",
    "serving_description": "3 cloves (9g)",
    "serving_mass_g": 9,
    "serving_volume_ml": 0,
    "calories": 13,
    "protein_g": 0.6,
    "fat_g": 0,
    "carbs_g": 3,
    "sugar_g": 0.1,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 34,
    "name": "Mushrooms",
    "serving_description": "1 cup sliced (70g)",
    "serving_mass_g": 70,
    "serving_volume_ml": 0,
    "calories": 15,
    "protein_g": 2.2,
    "fat_g": 0.2,
    "carbs_g": 2.3,
    "sugar_g": 1.4,
    "sodium_mg": 4,
    "cholesterol_mg": 0
  },
  {
    "id": 35,
    "name": "Corn (sweet)",
    "serving_description": "1 ear (90g)",
    "serving_mass_g": 90,
    "serving_volume_ml": 0,
    "calories": 77,
    "protein_g": 2.9,
    "fat_g": 1.1,
    "carbs_g": 17,
    "sugar_g": 6.4,
    "sodium_mg": 15,
    "cholesterol_mg": 0
  },
  {
    "id": 36,
    "name": "Peas",
    "serving_description": "1 cup (160g)",
    "serving_mass_g": 160,
    "serving_volume_ml": 0,
    "calories": 117,
    "protein_g": 8,
    "fat_g": 0.6,
    "carbs_g": 21,
    "sugar_g": 8,
    "sodium_mg": 7,
    "cholesterol_mg": 0
  },
  {
    "id": 37,
    "name": "Yogurt (plain)",
    "serving_description": "1 cup (245g)",
    "serving_mass_g": 245,
    "serving_volume_ml": 240,
    "calories": 149,
    "protein_g": 8.5,
    "fat_g": 8,
    "carbs_g": 11,
    "sugar_g": 11,
    "sodium_mg": 113,
    "cholesterol_mg": 31
  },
  {
    "id": 38,
    "name": "Cottage Cheese",
    "serving_description": "1/2 cup (113g)",
    "serving_mass_g": 113,
    "serving_volume_ml": 0,
    "calories": 98,
    "protein_g": 11,
    "fat_g": 4.3,
    "carbs_g": 3.4,
    "sugar_g": 2.7,
    "sodium_mg": 364,
    "cholesterol_mg": 17
  },
  {
    "id": 39,
    "name": "Mozzarella Cheese",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 85,
    "protein_g": 6.3,
    "fat_g": 6.3,
    "carbs_g": 1,
    "sugar_g": 0.3,
    "sodium_mg": 138,
    "cholesterol_mg": 22
  },
  {
    "id": 40,
    "name": "Ham",
    "serving_description": "3 oz (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 105,
    "protein_g": 14,
    "fat_g": 4,
    "carbs_g": 1.5,
    "sugar_g": 1.5,
    "sodium_mg": 830,
    "cholesterol_mg": 38
  },
  {
    "id": 41,
    "name": "Turkey Breast",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 125,
    "protein_g": 26,
    "fat_g": 1,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 55,
    "cholesterol_mg": 62
  },
  {
    "id": 42,
    "name": "Pork Bacon",
    "serving_description": "2 slices (16g)",
    "serving_mass_g": 16,
    "serving_volume_ml": 0,
    "calories": 87,
    "protein_g": 6,
    "fat_g": 7,
    "carbs_g": 0.2,
    "sugar_g": 0,
    "sodium_mg": 376,
    "cholesterol_mg": 18
  },
  {
    "id": 43,
    "name": "Tortilla (corn)",
    "serving_description": "1 tortilla (24g)",
    "serving_mass_g": 24,
    "serving_volume_ml": 0,
    "calories": 52,
    "protein_g": 1.4,
    "fat_g": 0.7,
    "carbs_g": 11,
    "sugar_g": 0.2,
    "sodium_mg": 11,
    "cholesterol_mg": 0
  },
  {
    "id": 44,
    "name": "Tortilla (wheat)",
    "serving_description": "1 tortilla (36g)",
    "serving_mass_g": 36,
    "serving_volume_ml": 0,
    "calories": 110,
    "protein_g": 3.7,
    "fat_g": 2.5,
    "carbs_g": 19,
    "sugar_g": 1.1,
    "sodium_mg": 210,
    "cholesterol_mg": 0
  },
  {
    "id": 45,
    "name": "Pizza (cheese slice)",
    "serving_description": "1 slice (107g)",
    "serving_mass_g": 107,
    "serving_volume_ml": 0,
    "calories": 285,
    "protein_g": 12,
    "fat_g": 10,
    "carbs_g": 36,
    "sugar_g": 4,
    "sodium_mg": 640,
    "cholesterol_mg": 18
  },
  {
    "id": 46,
    "name": "Hamburger (beef patty)",
    "serving_description": "1 sandwich (100g)",
    "serving_mass_g": 100,
    "serving_volume_ml": 0,
    "calories": 254,
    "protein_g": 12,
    "fat_g": 9,
    "carbs_g": 29,
    "sugar_g": 5,
    "sodium_mg": 511,
    "cholesterol_mg": 35
  },
  {
    "id": 47,
    "name": "Hot Dog",
    "serving_description": "1 hot dog (52g)",
    "serving_mass_g": 52,
    "serving_volume_ml": 0,
    "calories": 151,
    "protein_g": 5,
    "fat_g": 13,
    "carbs_g": 2,
    "sugar_g": 1,
    "sodium_mg": 507,
    "cholesterol_mg": 30
  },
  {
    "id": 48,
    "name": "French Fries",
    "serving_description": "1 medium (117g)",
    "serving_mass_g": 117,
    "serving_volume_ml": 0,
    "calories": 365,
    "protein_g": 3.4,
    "fat_g": 17,
    "carbs_g": 48,
    "sugar_g": 0.3,
    "sodium_mg": 246,
    "cholesterol_mg": 0
  },
  {
    "id": 49,
    "name": "Tortilla Chips",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 138,
    "protein_g": 2,
    "fat_g": 7,
    "carbs_g": 18,
    "sugar_g": 0.1,
    "sodium_mg": 115,
    "cholesterol_mg": 0
  },
  {
    "id": 50,
    "name": "Chocolate Bar",
    "serving_description": "1 bar (43g)",
    "serving_mass_g": 43,
    "serving_volume_ml": 0,
    "calories": 210,
    "protein_g": 2,
    "fat_g": 13,
    "carbs_g": 25,
    "sugar_g": 24,
    "sodium_mg": 35,
    "cholesterol_mg": 8
  },
  {
    "id": 51,
    "name": "Ice Cream (vanilla scoop)",
    "serving_description": "1/2 cup (66g)",
    "serving_mass_g": 66,
    "serving_volume_ml": 0,
    "calories": 137,
    "protein_g": 2.3,
    "fat_g": 7.3,
    "carbs_g": 16,
    "sugar_g": 14,
    "sodium_mg": 53,
    "cholesterol_mg": 29
  },
  {
    "id": 52,
    "name": "Peanut Butter",
    "serving_description": "2 tbsp (32g)",
    "serving_mass_g": 32,
    "serving_volume_ml": 0,
    "calories": 188,
    "protein_g": 8,
    "fat_g": 16,
    "carbs_g": 6,
    "sugar_g": 3,
    "sodium_mg": 136,
    "cholesterol_mg": 0
  },
  {
    "id": 53,
    "name": "Almonds",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 164,
    "protein_g": 6,
    "fat_g": 14,
    "carbs_g": 6,
    "sugar_g": 1.2,
    "sodium_mg": 0,
    "cholesterol_mg": 0
  },
  {
    "id": 54,
    "name": "Walnuts",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 185,
    "protein_g": 4.3,
    "fat_g": 18,
    "carbs_g": 4,
    "sugar_g": 0.7,
    "sodium_mg": 1,
    "cholesterol_mg": 0
  },
  {
    "id": 55,
    "name": "Cashews",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 157,
    "protein_g": 5,
    "fat_g": 12,
    "carbs_g": 9,
    "sugar_g": 1.7,
    "sodium_mg": 3,
    "cholesterol_mg": 0
  },
  {
    "id": 56,
    "name": "Bread (white)",
    "serving_description": "1 slice (25g)",
    "serving_mass_g": 25,
    "serving_volume_ml": 0,
    "calories": 67,
    "protein_g": 2,
    "fat_g": 0.8,
    "carbs_g": 13,
    "sugar_g": 1.4,
    "sodium_mg": 127,
    "cholesterol_mg": 0
  },
  {
    "id": 57,
    "name": "Bagel",
    "serving_description": "1 medium (98g)",
    "serving_mass_g": 98,
    "serving_volume_ml": 0,
    "calories": 277,
    "protein_g": 11,
    "fat_g": 1.4,
    "carbs_g": 55,
    "sugar_g": 6,
    "sodium_mg": 443,
    "cholesterol_mg": 0
  },
  {
    "id": 58,
    "name": "Cereal (corn flakes)",
    "serving_description": "1 cup (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 100,
    "protein_g": 2,
    "fat_g": 0.1,
    "carbs_g": 24,
    "sugar_g": 2.7,
    "sodium_mg": 200,
    "cholesterol_mg": 0
  },
  {
    "id": 59,
    "name": "Granola",
    "serving_description": "1/2 cup (50g)",
    "serving_mass_g": 50,
    "serving_volume_ml": 0,
    "calories": 200,
    "protein_g": 4,
    "fat_g": 6,
    "carbs_g": 32,
    "sugar_g": 12,
    "sodium_mg": 60,
    "cholesterol_mg": 0
  },
  {
    "id": 60,
    "name": "Pancakes (2 medium)",
    "serving_description": "2 medium (86g)",
    "serving_mass_g": 86,
    "serving_volume_ml": 0,
    "calories": 175,
    "protein_g": 4.8,
    "fat_g": 4.8,
    "carbs_g": 28,
    "sugar_g": 4.2,
    "sodium_mg": 420,
    "cholesterol_mg": 38
  },
  {
    "id": 61,
    "name": "Waffles (2)",
    "serving_description": "2 waffles (70g)",
    "serving_mass_g": 70,
    "serving_volume_ml": 0,
    "calories": 218,
    "protein_g": 5.6,
    "fat_g": 7,
    "carbs_g": 33,
    "sugar_g": 6,
    "sodium_mg": 383,
    "cholesterol_mg": 38
  },
  {
    "id": 62,
    "name": "French Toast (1 slice)",
    "serving_description": "1 slice (65g)",
    "serving_mass_g": 65,
    "serving_volume_ml": 0,
    "calories": 149,
    "protein_g": 6.4,
    "fat_g": 5.4,
    "carbs_g": 19,
    "sugar_g": 4.2,
    "sodium_mg": 210,
    "cholesterol_mg": 99
  },
  {
    "id": 63,
    "name": "Coffee (8oz)",
    "serving_description": "1 cup (237ml)",
    "serving_mass_g": 237,
    "serving_volume_ml": 237,
    "calories": 2,
    "protein_g": 0.3,
    "fat_g": 0,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 5,
    "cholesterol_mg": 0
  },
  {
    "id": 64,
    "name": "Tea (8oz)",
    "serving_description": "1 cup (237ml)",
    "serving_mass_g": 237,
    "serving_volume_ml": 237,
    "calories": 2,
    "protein_g": 0,
    "fat_g": 0,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 7,
    "cholesterol_mg": 0
  },
  {
    "id": 65,
    "name": "Orange Juice (8oz)",
    "serving_description": "1 cup (240ml)",
    "serving_mass_g": 240,
    "serving_volume_ml": 240,
    "calories": 112,
    "protein_g": 1.7,
    "fat_g": 0.5,
    "carbs_g": 26,
    "sugar_g": 21,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 66,
    "name": "Soda (12oz)",
    "serving_description": "1 can (355ml)",
    "serving_mass_g": 355,
    "serving_volume_ml": 355,
    "calories": 140,
    "protein_g": 0,
    "fat_g": 0,
    "carbs_g": 39,
    "sugar_g": 39,
    "sodium_mg": 45,
    "cholesterol_mg": 0
  },
  {
    "id": 67,
    "name": "Beer (12oz)",
    "serving_description": "1 can (355ml)",
    "serving_mass_g": 355,
    "serving_volume_ml": 355,
    "calories": 153,
    "protein_g": 1.6,
    "fat_g": 0,
    "carbs_g": 13,
    "sugar_g": 0,
    "sodium_mg": 14,
    "cholesterol_mg": 0
  },
  {
    "id": 68,
    "name": "Wine (5oz)",
    "serving_description": "5 oz (147ml)",
    "serving_mass_g": 147,
    "serving_volume_ml": 147,
    "calories": 123,
    "protein_g": 0.1,
    "fat_g": 0,
    "carbs_g": 4,
    "sugar_g": 1,
    "sodium_mg": 5,
    "cholesterol_mg": 0
  },
  {
    "id": 69,
    "name": "Water (500ml)",
    "serving_description": "500ml",
    "serving_mass_g": 500,
    "serving_volume_ml": 500,
    "calories": 0,
    "protein_g": 0,
    "fat_g": 0,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 0,
    "cholesterol_mg": 0
  },
  {
    "id": 70,
    "name": "Tofu",
    "serving_description": "1/2 cup (126g)",
    "serving_mass_g": 126,
    "serving_volume_ml": 0,
    "calories": 94,
    "protein_g": 10,
    "fat_g": 6,
    "carbs_g": 2.3,
    "sugar_g": 0.6,
    "sodium_mg": 9,
    "cholesterol_mg": 0
  },
  {
    "id": 71,
    "name": "Tempeh",
    "serving_description": "1/2 cup (83g)",
    "serving_mass_g": 83,
    "serving_volume_ml": 0,
    "calories": 160,
    "protein_g": 15,
    "fat_g": 9,
    "carbs_g": 9,
    "sugar_g": 0,
    "sodium_mg": 9,
    "cholesterol_mg": 0
  },
  {
    "id": 72,
    "name": "Edamame",
    "serving_description": "1/2 cup shelled (78g)",
    "serving_mass_g": 78,
    "serving_volume_ml": 0,
    "calories": 94,
    "protein_g": 9,
    "fat_g": 4,
    "carbs_g": 7,
    "sugar_g": 2,
    "sodium_mg": 4,
    "cholesterol_mg": 0
  },
  {
    "id": 73,
    "name": "Quinoa",
    "serving_description": "1 cup cooked (185g)",
    "serving_mass_g": 185,
    "serving_volume_ml": 0,
    "calories": 222,
    "protein_g": 8.1,
    "fat_g": 3.6,
    "carbs_g": 39,
    "sugar_g": 1.6,
    "sodium_mg": 13,
    "cholesterol_mg": 0
  },
  {
    "id": 74,
    "name": "Barley",
    "serving_description": "1 cup cooked (157g)",
    "serving_mass_g": 157,
    "serving_volume_ml": 0,
    "calories": 193,
    "protein_g": 3.6,
    "fat_g": 0.7,
    "carbs_g": 44,
    "sugar_g": 0.4,
    "sodium_mg": 6,
    "cholesterol_mg": 0
  },
  {
    "id": 75,
    "name": "Millet",
    "serving_description": "1 cup cooked (174g)",
    "serving_mass_g": 174,
    "serving_volume_ml": 0,
    "calories": 207,
    "protein_g": 6.1,
    "fat_g": 1.7,
    "carbs_g": 41,
    "sugar_g": 0.2,
    "sodium_mg": 3,
    "cholesterol_mg": 0
  },
  {
    "id": 76,
    "name": "Couscous",
    "serving_description": "1 cup cooked (157g)",
    "serving_mass_g": 157,
    "serving_volume_ml": 0,
    "calories": 176,
    "protein_g": 6,
    "fat_g": 0.3,
    "carbs_g": 36,
    "sugar_g": 0.2,
    "sodium_mg": 8,
    "cholesterol_mg": 0
  },
  {
    "id": 77,
    "name": "Sausage (pork link)",
    "serving_description": "1 link (45g)",
    "serving_mass_g": 45,
    "serving_volume_ml": 0,
    "calories": 148,
    "protein_g": 5.5,
    "fat_g": 13,
    "carbs_g": 1.1,
    "sugar_g": 0.7,
    "sodium_mg": 379,
    "cholesterol_mg": 30
  },
  {
    "id": 78,
    "name": "Salami",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 110,
    "protein_g": 6,
    "fat_g": 9,
    "carbs_g": 0.5,
    "sugar_g": 0.2,
    "sodium_mg": 430,
    "cholesterol_mg": 24
  },
  {
    "id": 79,
    "name": "Pepperoni",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 138,
    "protein_g": 5.5,
    "fat_g": 12,
    "carbs_g": 0.6,
    "sugar_g": 0.1,
    "sodium_mg": 493,
    "cholesterol_mg": 20
  },
  {
    "id": 80,
    "name": "Meatballs (beef)",
    "serving_description": "3 medium (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 200,
    "protein_g": 14,
    "fat_g": 14,
    "carbs_g": 4,
    "sugar_g": 1,
    "sodium_mg": 400,
    "cholesterol_mg": 60
  },
  {
    "id": 81,
    "name": "Fish (cod)",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 70,
    "protein_g": 15,
    "fat_g": 0.6,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 60,
    "cholesterol_mg": 37
  },
  {
    "id": 82,
    "name": "Shrimp (fried)",
    "serving_description": "3 oz (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 206,
    "protein_g": 13,
    "fat_g": 13,
    "carbs_g": 10,
    "sugar_g": 0.5,
    "sodium_mg": 570,
    "cholesterol_mg": 130
  },
  {
    "id": 83,
    "name": "Chicken Thigh",
    "serving_description": "1 thigh (80g)",
    "serving_mass_g": 80,
    "serving_volume_ml": 0,
    "calories": 109,
    "protein_g": 13,
    "fat_g": 6,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 50,
    "cholesterol_mg": 63
  },
  {
    "id": 84,
    "name": "Duck Breast",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 170,
    "protein_g": 23,
    "fat_g": 8,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 55,
    "cholesterol_mg": 76
  },
  {
    "id": 85,
    "name": "Lamb Chop",
    "serving_description": "1 chop (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 210,
    "protein_g": 17,
    "fat_g": 15,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 53,
    "cholesterol_mg": 65
  },
  {
    "id": 86,
    "name": "Beef Steak (sirloin)",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 180,
    "protein_g": 24,
    "fat_g": 8,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 55,
    "cholesterol_mg": 70
  },
  {
    "id": 87,
    "name": "Beef Steak (ribeye)",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 210,
    "protein_g": 23,
    "fat_g": 13,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 55,
    "cholesterol_mg": 70
  },
  {
    "id": 88,
    "name": "Pork Ribs",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 270,
    "protein_g": 20,
    "fat_g": 20,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 75,
    "cholesterol_mg": 70
  },
  {
    "id": 89,
    "name": "Clams",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 126,
    "protein_g": 22,
    "fat_g": 2,
    "carbs_g": 4,
    "sugar_g": 0,
    "sodium_mg": 95,
    "cholesterol_mg": 57
  },
  {
    "id": 90,
    "name": "Oysters",
    "serving_description": "6 medium (84g)",
    "serving_mass_g": 84,
    "serving_volume_ml": 0,
    "calories": 69,
    "protein_g": 8,
    "fat_g": 2,
    "carbs_g": 4,
    "sugar_g": 0,
    "sodium_mg": 90,
    "cholesterol_mg": 42
  },
  {
    "id": 91,
    "name": "Mussels",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 146,
    "protein_g": 20,
    "fat_g": 4,
    "carbs_g": 6,
    "sugar_g": 0,
    "sodium_mg": 286,
    "cholesterol_mg": 48
  },
  {
    "id": 92,
    "name": "Crab",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 71,
    "protein_g": 15,
    "fat_g": 0.8,
    "carbs_g": 0,
    "sugar_g": 0,
    "sodium_mg": 321,
    "cholesterol_mg": 45
  },
  {
    "id": 93,
    "name": "Lobster",
    "serving_description": "3 oz cooked (85g)",
    "serving_mass_g": 85,
    "serving_volume_ml": 0,
    "calories": 76,
    "protein_g": 16,
    "fat_g": 0.7,
    "carbs_g": 1.1,
    "sugar_g": 0,
    "sodium_mg": 423,
    "cholesterol_mg": 72
  },
  {
    "id": 94,
    "name": "Pumpkin",
    "serving_description": "1 cup cooked (245g)",
    "serving_mass_g": 245,
    "serving_volume_ml": 0,
    "calories": 49,
    "protein_g": 2,
    "fat_g": 0.2,
    "carbs_g": 12,
    "sugar_g": 5,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 95,
    "name": "Zucchini",
    "serving_description": "1 cup sliced (124g)",
    "serving_mass_g": 124,
    "serving_volume_ml": 0,
    "calories": 21,
    "protein_g": 1.5,
    "fat_g": 0.4,
    "carbs_g": 3.9,
    "sugar_g": 2.4,
    "sodium_mg": 9,
    "cholesterol_mg": 0
  },
  {
    "id": 96,
    "name": "Eggplant",
    "serving_description": "1 cup cooked (99g)",
    "serving_mass_g": 99,
    "serving_volume_ml": 0,
    "calories": 35,
    "protein_g": 0.8,
    "fat_g": 0.2,
    "carbs_g": 8.6,
    "sugar_g": 3.2,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 97,
    "name": "Cabbage",
    "serving_description": "1 cup chopped (89g)",
    "serving_mass_g": 89,
    "serving_volume_ml": 0,
    "calories": 22,
    "protein_g": 1.1,
    "fat_g": 0.1,
    "carbs_g": 5.2,
    "sugar_g": 2.8,
    "sodium_mg": 16,
    "cholesterol_mg": 0
  },
  {
    "id": 98,
    "name": "Kale",
    "serving_description": "1 cup chopped (67g)",
    "serving_mass_g": 67,
    "serving_volume_ml": 0,
    "calories": 33,
    "protein_g": 2.2,
    "fat_g": 0.6,
    "carbs_g": 6,
    "sugar_g": 1.3,
    "sodium_mg": 25,
    "cholesterol_mg": 0
  },
  {
    "id": 99,
    "name": "Lettuce",
    "serving_description": "1 cup shredded (36g)",
    "serving_mass_g": 36,
    "serving_volume_ml": 0,
    "calories": 5,
    "protein_g": 0.5,
    "fat_g": 0.1,
    "carbs_g": 1,
    "sugar_g": 0.5,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 100,
    "name": "Rice Cakes",
    "serving_description": "1 cake (9g)",
    "serving_mass_g": 9,
    "serving_volume_ml": 0,
    "calories": 35,
    "protein_g": 0.7,
    "fat_g": 0.1,
    "carbs_g": 7.3,
    "sugar_g": 0,
    "sodium_mg": 7,
    "cholesterol_mg": 0
  },
  {
    "id": 101,
    "name": "Popcorn (air-popped)",
    "serving_description": "3 cups (24g)",
    "serving_mass_g": 24,
    "serving_volume_ml": 0,
    "calories": 93,
    "protein_g": 3,
    "fat_g": 1.1,
    "carbs_g": 18.6,
    "sugar_g": 0.2,
    "sodium_mg": 2,
    "cholesterol_mg": 0
  },
  {
    "id": 102,
    "name": "Pretzels",
    "serving_description": "1 oz (28g)",
    "serving_mass_g": 28,
    "serving_volume_ml": 0,
    "calories": 108,
    "protein_g": 2.7,
    "fat_g": 0.8,
    "carbs_g": 22,
    "sugar_g": 0.8,
    "sodium_mg": 354,
    "cholesterol_mg": 0
  },
  {
    "id": 103,
    "name": "Granola Bar",
    "serving_description": "1 bar (24g)",
    "serving_mass_g": 24,
    "serving_volume_ml": 0,
    "calories": 100,
    "protein_g": 2,
    "fat_g": 3,
    "carbs_g": 17,
    "sugar_g": 7,
    "sodium_mg": 65,
    "cholesterol_mg": 0
  },
  {
    "id": 104,
    "name": "Protein Shake",
    "serving_description": "1 scoop (30g) with water",
    "serving_mass_g": 30,
    "serving_volume_ml": 0,
    "calories": 120,
    "protein_g": 24,
    "fat_g": 1,
    "carbs_g": 3,
    "sugar_g": 1,
    "sodium_mg": 50,
    "cholesterol_mg": 50
  },
  {
    "id": 105,
    "name": "Smoothie",
    "serving_description": "1 cup (240ml)",
    "serving_mass_g": 240,
    "serving_volume_ml": 240,
    "calories": 130,
    "protein_g": 2,
    "fat_g": 1,
    "carbs_g": 31,
    "sugar_g": 23,
    "sodium_mg": 20,
    "cholesterol_mg": 0
  }
];
